### ISSUE TITLE
[Bug]: Problem with ControlNet 'UiControlNetUnit' has no attribute 'from_dict'

### ISSUE THREAD

**Issue by andrefromsbg** [deforum-art/sd-forge-deforum#10]
### What happened and why was it ungood?

Trying to run deforum but I always get this error: 

```
*START OF TRACEBACK*
Traceback (most recent call last):
  File "C:\Users\Andre\Apps\webui_forge_cu121_torch21\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\run_deforum.py", line 116, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, freeu_args, root)
  File "C:\Users\Andre\Apps\webui_forge_cu121_torch21\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\render.py", line 585, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, freeu_args, root, parseq_adapter, frame_idx, sampler_name=scheduled_sampler_name)
  File "C:\Users\Andre\Apps\webui_forge_cu121_torch21\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\generate.py", line 80, in generate
    return generate_inner(args, keys, anim_args, loop_args, controlnet_args, freeu_args, root, parseq_adapter, frame, sampler_name)
  File "C:\Users\Andre\Apps\webui_forge_cu121_torch21\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\generate.py", line 242, in generate_inner
    cnet_args = get_controlnet_script_args(args, anim_args, controlnet_args, root, parseq_adapter, frame_idx=frame)
  File "C:\Users\Andre\Apps\webui_forge_cu121_torch21\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\deforum_controlnet.py", line 270, in get_controlnet_script_args
    units = [
  File "C:\Users\Andre\Apps\webui_forge_cu121_torch21\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\deforum_controlnet.py", line 271, in <listcomp>
    ControlNetUnit.from_dict(create_cnu_dict(controlnet_args, f"cn_{i + 1}", img_np, mask_np, frame_idx, CnSchKeys))
AttributeError: type object 'UiControlNetUnit' has no attribute 'from_dict'
*END OF TRACEBACK*

User friendly error message:
Error: type object 'UiControlNetUnit' has no attribute 'from_dict'. Please, check your schedules/ init values.
```

Everything worked just fine with the same settings before switching to forge. Any advices? Thanks!

**Comment by andrefromsbg** [comment]
Updating fixed it, my bad.

**Comment by The-ShadowWalker** [comment]
> Updating fixed it, my bad.

I am getting the same problem.


*START OF TRACEBACK*
Traceback (most recent call last):
  File "D:\Users\Stable diffusion Forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\run_deforum.py", line 116, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root)
  File "D:\Users\Stable diffusion Forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\render.py", line 591, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root, parseq_adapter, frame_idx, sampler_name=scheduled_sampler_name)
  File "D:\Users\Stable diffusion Forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\generate.py", line 80, in generate
    return generate_inner(args, keys, anim_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root, parseq_adapter, frame, sampler_name)
  File "D:\Users\Stable diffusion Forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\generate.py", line 242, in generate_inner
    cnet_args = get_controlnet_script_args(args, anim_args, controlnet_args, root, parseq_adapter, frame_idx=frame)
  File "D:\Users\Stable diffusion Forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\deforum_controlnet.py", line 263, in get_controlnet_script_args
    units = [
  File "D:\Users\Stable diffusion Forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\deforum_controlnet.py", line 264, in <listcomp>
    ControlNetUnit.from_dict(create_cnu_dict(controlnet_args, f"cn_{i + 1}", img_np, mask_np, frame_idx, CnSchKeys))
AttributeError: type object 'UiControlNetUnit' has no attribute 'from_dict'
*END OF TRACEBACK*

User friendly error message:
Error: type object 'UiControlNetUnit' has no attribute 'from_dict'. Please, check your schedules/ init values.


thanks for you help
