### ISSUE TITLE
[Bug]: Image cannot generate, when using controlnet. with  (--unet-in-fp8-e4m3fn) in the command line

### ISSUE THREAD

**Issue by Shiba-2-shiba** [deforum-art/sd-forge-deforum#2]
### What happened and why was it ungood?

When I use (--unet-in-fp8-e4m3fn) in the command line, the following error occurs, and I cannot generate images. 
This error only occurs when using the control net and does not occur when not using the control net.
Using the control net in the usual txt2img can also generate images with this command line.

The error code is as follows

2024-02-22 02:30:33,594 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-22 02:30:33,595 - ControlNet - INFO - Using preprocessor: blur_gaussian
2024-02-22 02:30:33,595 - ControlNet - INFO - preprocessor resolution = 768
2024-02-22 02:30:33,640 - ControlNet - INFO - Current ControlNet ControlLLLitePatcher: /notebooks/stable-diffusion-webui-forge/models/ControlNet/kohya_controllllite_xl_blur_anime.safetensors
136 modules
2024-02-22 02:30:34,043 - ControlNet - INFO - ControlNet Method blur_gaussian patched.
To load target model SDXL
Begin to load 1 model
unload clone 1
Moving model(s) has taken 1.23 seconds
  0%|                                                     | 0/4 [00:00<?, ?it/s]
WARNING:deforum_helpers.opts_overrider:Error during batch execution: <class 'RuntimeError'> - Input type (c10::Half) and bias type (c10::Float8_e4m3fn) should be the same

*START OF TRACEBACK*
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/run_deforum.py", line 116, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "/notebooks/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/render.py", line 577, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame_idx, sampler_name=scheduled_sampler_name)
  File "/notebooks/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/generate.py", line 78, in generate
    return generate_inner(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame, sampler_name)
  File "/notebooks/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/generate.py", line 283, in generate_inner
    processed = processing.process_images(p)
  File "/notebooks/stable-diffusion-webui-forge/modules/processing.py", line 750, in process_images
    res = process_images_inner(p)
  File "/notebooks/stable-diffusion-webui-forge/modules/processing.py", line 921, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/notebooks/stable-diffusion-webui-forge/modules/processing.py", line 1704, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/notebooks/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 197, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/notebooks/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "/notebooks/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 197, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui-forge/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "/notebooks/stable-diffusion-webui-forge/modules_forge/forge_sampler.py", line 82, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/modules/samplers.py", line 289, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/modules/samplers.py", line 258, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/modules/model_base.py", line 89, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 867, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 55, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/ldm/modules/attention.py", line 620, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/ldm/modules/attention.py", line 447, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/ldm/modules/diffusionmodules/util.py", line 194, in checkpoint
    return func(*inputs)
  File "/notebooks/stable-diffusion-webui-forge/ldm_patched/ldm/modules/attention.py", line 486, in _forward
    n, context_attn1, value_attn1 = p(n, context_attn1, value_attn1, extra_options)
  File "/notebooks/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlllite/lib_controllllite/lib_controllllite.py", line 102, in __call__
    q = q + self.modules[module_pfx_to_q](q)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlllite/lib_controllllite/lib_controllllite.py", line 216, in forward
    cx = self.conditioning1(self.cond_image.to(x.device, dtype=x.dtype))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (c10::Float8_e4m3fn) should be the same
*END OF TRACEBACK*

User friendly error message:
Error: Input type (c10::Half) and bias type (c10::Float8_e4m3fn) should be the same. Please, check your schedules/ init values.
Deforum progress:  11%|██▊                      | 10/90 [00:04<00:37,  2.12it/s]

**Comment by Shiba-2-shiba** [comment]
As for this bug, the IP-adapter can be used without any problem.
