### ISSUE TITLE
[Bug]: *** Error executing callback ui_tabs_callback

### ISSUE THREAD

**Issue by dron28** [deforum-art/sd-forge-deforum#23]
for C:\forge\webui\extensions\sd-forge-deforum\scripts\deforum.py
Traceback (most recent call last):
File "C:\forge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
res += c.callback() or []
File "C:\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\ui_right.py", line 38, in on_ui_tabs
with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
AttributeError: 'Row' object has no attribute 'style'

**Comment by Bladed3d** [comment]
Same problem. Pinokio announced forge webui implementation, but after adding the deforum extension, I got error:
Forge with Flux working in Pinokio (Hurray!) but after adding Deforum extension, I get this error:
*** Error executing callback ui_tabs_callback for C:\pinokio\api\stable-diffusion-webui-forge.git\app\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
    Traceback (most recent call last):
      File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 38, in on_ui_tabs
        with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'

**Comment by alex2022cci** [comment]
You can replace 
` gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):`

by 
`gr.Row(elem_id='deforum_progress_row'):`

Also if you get a problem with 
` dummy_component = gr.Label(visible=False)`

you can replace the label by a textbox :
`dummy_component = gr.Textbox(visible=False)`

I hope it will help anybody with those problems.
