### ISSUE TITLE
[Bug]: control net does not work with SDXL

### ISSUE THREAD

**Issue by agustincaniglia** [deforum-art/sd-forge-deforum#6]
### What happened and why was it ungood?

does it? I am doing deforum animation okay, but when I use control net it doesn't work.

**Comment by rewbs** [comment]
Hi! I have used controlnet just fine with SDXL. Could you please confirm you are selecting an SDXL-compatible controlnet and include the error message from the terminal?

**Comment by GevatterWuff** [comment]
It did work for me last week before the recent update with images, now I'm getting:
`*** Error running process: H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\webuiforge2\webui\modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "H:\webuiforge2\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 548, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "H:\webuiforge2\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 322, in process_unit_after_click_generate
        preprocessor_output = preprocessor(
      File "H:\webuiforge2\webui\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
        result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
      File "H:\webuiforge2\webui\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 244, in leres
        img, remove_pad = resize_image_with_pad(img, res)
      File "H:\webuiforge2\webui\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 46, in resize_image_with_pad
        img = cv2.resize(img, (W_target, H_target), interpolation=interpolation)
    cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'


---
*** Error running process_before_every_sampling: H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\webuiforge2\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "H:\webuiforge2\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
 44%|███████████████████▌                        | 4/9 [00:00<00:01,  4.77it/s]
*** Error running postprocess_batch_list: H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\webuiforge2\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "H:\webuiforge2\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\webuiforge2\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---`

**Comment by GevatterWuff** [comment]
Update: I found out why some ControlNets are not working; some sliders don't show up.
There's a TODO comment about this problem in deforum_controlnet.py line 70.
To fix preprocessors like Leres you can set a fixed value for the resolution in line 83 but this method ruins other ControlNets like canny, so wait for the correct fix.

**Comment by rewbs** [comment]
> Update: I found out why some ControlNets are not working; some sliders don't show up. There's a TODO comment about this problem in deforum_controlnet.py line 70. To fix preprocessors like Leres you can set a fixed value for the resolution in line 83 but this method ruins other ControlNets like canny, so wait for the correct fix.

Thanks for that, you're absolutely right – the resolution preprocessor parameter was not being applied, which broke many preprocessors. Fix is in branch `rewbs/fix-controlnet-resolution-slider`, will merge shortly.

**Comment by rewbs** [comment]
Fix merged. Controlnet should be working now, assuming appropriate proprocessors and models are selected (the Deforum extension does not yet have a UI that helps you select correct preprocessor/model pairs).

Feel free to re-open or raise another bug if you continue to see issues. Thanks for the report and sorry about the delay.
